In [1]:
import numpy as np

In [ ]:
'''
正确图像
->A X A
  A'X'B'<-
相似图像
->C Y B
  C'Y'B'<-
引物
->A
    B'<-


->A Y B
'''


In [10]:
c1 = np.empty(10)
c2 = np.empty(10)

c1[0] = 1
c2[0] = 1

for i in range(9):
    c1[i+1] = c1[i] + c2[i]
    c2[i+1] = c2[i] + c1[i]

In [11]:
c1

array([  1.,   2.,   4.,   8.,  16.,  32.,  64., 128., 256., 512.])

In [12]:
c1 = np.empty(10)
c2 = np.empty(10)
c3 = np.empty(10)
c4 = np.empty(10)

c1[0] = 1
c2[0] = 1
c3[0] = 1
c4[0] = 1

for i in range(9):
    c1[i+1] = c1[i]
    c2[i+1] = c2[i] + c1[i]
    c3[i+1] = c3[i] + c4[i] + 0.5*c2[i]
    c4[i+1] = c4[i] + c3[i]

In [14]:
c2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [15]:
c3

array([  1. ,   2.5,   5.5,  11.5,  23.5,  47.5,  95.5, 191.5, 383.5,
       767.5])

In [16]:
c4

array([  1. ,   2. ,   4.5,  10. ,  21.5,  45. ,  92.5, 188. , 379.5,
       763. ])